name: test_env_xrDMD
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - dask
  - numpy
  - numpy_groupies
  - scipy
  - pytest
  - pytest-cov
  - pip
  - cftime
  - xrft
  - pip:
    - codecov
    - pytest-xdist
